#!/usr/bin/env bash

set -eu

# Function to handle errors
err() {
  error_messsage="$@"
  echo -e "\033[1;31m ERROR:\033[0m ${error_messsage}" >&2
  exit 1
}

# define variable to hold public key
public_key_file=""

# check to see the correct number of arguments have been passed to your script
if [[ $# -ne 1 ]]; then
  err "script requires the path to the public key file you would like to import"
fi

# check to see if the public key file passed as the first positional parameter is a regular file
if [[ ! -f $1 ]]; then
  err "path to public key for import is incorrect, file does not exist"
else
  public_key_file="$1"
fi

# use aws to import the public key into aws account, write info about import to key_data file
# FIXED: Changed key-name to "bcitkey"
aws ec2 import-key-pair --key-name "bcitkey" --public-key-material fileb://${public_key_file} > key_data